name: Getir Task- Cat Fact Api Automation
on:
  schedule:
  - cron: 0 8 * * *
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v1
      with: 
        node-version: '14.x'
    - name: Install newman
      run: |
       npm install -g newman
       npm install -g newman-reporter-htmlextra
    - name: Make Directory for results
      run: mkdir -p testResults
    - name: Run POSTMAN collection
      run: |
       newman run CatFactAPI.postman_collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html
    - name: Output the run Details
      if: always()
      uses: actions/upload-artifact@v2
      with: 
       name: RunReports
       path: testResults/htmlreport.html
